trigger:
  branches:
    include:
      - main
  paths:
    include:
      - aplicacao/**

pool:
  vmImage: ubuntu-latest

variables:
  DOTNET_VERSION: '8.x'
  PROJECT_PATH: 'KomercioApi.csproj'
  DEPLOY_PATH: '/home/azureuser/komercio/estoque'

stages:
- stage: Build
  displayName: Build .NET API
  jobs:
  - job: BuildJob
    displayName: Compilar Estoque Service
    steps:

    - task: UseDotNet@2
      displayName: 'Instalar .NET $(DOTNET_VERSION)'
      inputs:
        version: $(DOTNET_VERSION)

 
    - task: SonarQubePrepare@8
      inputs:
        SonarQube: 'Sonar'
        scannerMode: 'dotnet'
        projectKey: 'komercio-Sonar'
        projectName: 'Komercio'


    - script: |
        dotnet restore $(PROJECT_PATH)
        dotnet build $(PROJECT_PATH) -c Release
      displayName: 'Executar Build'

  
    - task: SonarQubeAnalyze@8
      inputs:
        jdkversion: 'JAVA_HOME_17_X64'

 
    - task: SonarQubePublish@8
      inputs:
        pollingTimeoutSec: '300'


    - script: |
        dotnet publish $(PROJECT_PATH) -c Release -o $(Build.ArtifactStagingDirectory)/publish
      displayName: 'Executar Dotnet Publish'

    - task: PublishPipelineArtifact@1
      displayName: 'Gerar Artefato'
      inputs:
        targetPath: $(Build.ArtifactStagingDirectory)/publish
        artifact: estoque_drop
